In [1]:
import torch
import torch.nn as nn

In [ ]:
#Hyperparams

embedding_dim= 3 
lr= 0.1

In [3]:
word_embeddings= torch.tensor([
    [0.2, 0.1, 0.3], #word1
    [0.5, 0.4, 0.6], #w2
    [0.9, 0.7, 0.8], #w3
    [1.2, 1.1, 1.0] #w4
], dtype= torch.float32)

positional_embeddings= nn.Parameter(torch.tensor([
    [0.1, 0.2, 0.3], #pos0
    [0.4, 0.5, 0.6], #pos1
    [0.7, 0.8, 0.9], #pos2
    [1.0, 1.1, 1.2] #pos3

], dtype=torch.float32, requires_grad=True))

In [4]:
y_true = torch.tensor([0.6, 0.9, 1.7, 2.5], dtype=torch.float32)

In [5]:
linear_layer= nn.Linear(embedding_dim, 1, bias=False) #y=xW.T 
linear_layer.weight.data.fill_(1.0) #weights=1


tensor([[1., 1., 1.]])

In [6]:
optimizer= torch.optim.SGD([positional_embeddings], lr=lr) #optimize positional embeddings

In [8]:
# Training

for epoch in range(20):
    optimizer.zero_grad()
    combined_embeddings= word_embeddings+ positional_embeddings
    y_pred= linear_layer(combined_embeddings).squeeze()
    loss= nn.MSELoss()(y_pred, y_true)

    loss.backward() #computes gradients loss wrt pos encodings
    optimizer.step() #updates pos encodings

    print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")
    print(f"Updated Positional Embeddings:\n{positional_embeddings.data}\n")

Epoch 1: Loss = 1.5351
Updated Positional Embeddings:
tensor([[-0.0246,  0.0754,  0.1754],
        [-0.0360,  0.0640,  0.1640],
        [ 0.0564,  0.1564,  0.2564],
        [ 0.1488,  0.2488,  0.3488]])

Epoch 2: Loss = 1.1091
Updated Positional Embeddings:
tensor([[-0.0359,  0.0641,  0.1641],
        [-0.0756,  0.0244,  0.1244],
        [-0.0021,  0.0979,  0.1979],
        [ 0.0715,  0.1715,  0.2715]])

Epoch 3: Loss = 0.8013
Updated Positional Embeddings:
tensor([[-0.0455,  0.0545,  0.1545],
        [-0.1093, -0.0093,  0.0907],
        [-0.0518,  0.0482,  0.1482],
        [ 0.0057,  0.1057,  0.2057]])

Epoch 4: Loss = 0.5790
Updated Positional Embeddings:
tensor([[-0.0537,  0.0463,  0.1463],
        [-0.1379, -0.0379,  0.0621],
        [-0.0940,  0.0060,  0.1060],
        [-0.0501,  0.0499,  0.1499]])

Epoch 5: Loss = 0.4183
Updated Positional Embeddings:
tensor([[-0.0606,  0.0394,  0.1394],
        [-0.1622, -0.0622,  0.0378],
        [-0.1299, -0.0299,  0.0701],
        [-0.0976,  

In [9]:
print('y_true: ', y_true)
print('y_pred: ',y_pred)

y_true:  tensor([0.6000, 0.9000, 1.7000, 2.5000])
y_pred:  tensor([0.6121, 0.9425, 1.7627, 2.5830], grad_fn=<SqueezeBackward0>)
